### ISSUE TITLE
[ports.py] regexp not matching potential server name

### ISSUE THREAD

**Issue by bpil** [VIRL-Open/virl-utils#12]
Ports.py used on a CML installation (UWM states VIRL v 0.10.13.29).

Started project may have a name not matching the regular expression in line 27 of ports.py . They may contain a "_" in the project descriptor not matching the [0-9a-z]+ part. Example found : "My_Topologies@MultiASTopo-2-oowt_Y". 
This result in some servers not being listed.

Replacing line 27 as such 
prog=re.compile(r'</(.*)/endpoint>-<(.*)-[0-9a-z_]+>-<(.*)>', re.IGNORECASE)
fixes it.

**Comment by rschmied** [comment]
Thanks for the comment. In fact, the RE did include the underscore for the Icehouse OpenStack and older STD release (which is still in use on CML). You could get the earlier version (or use your local version).

**Comment by rschmied** [comment]
closing this issue.
