### ISSUE TITLE
Integration of this script in your collection

### ISSUE THREAD

**Issue by gustavooferreira** [VIRL-Open/virl-utils#13]
Hello guys,

Any possibility you can integrate this script in your collection?

https://github.com/gustavooferreira/lcVIRL

It can be used with **wireshark** or any other tool, and it can be ran multiple times to capture on multiple ports. (It runs on Linux and Mac OS X)

Thanks in advance!

**Comment by rschmied** [comment]
Hey, Gustavo. Sure, why not. Why not open a PR? Or should I simply copy the script and include it into the repository? I could also put a link into the virl-utils README to link your script. Whatever works for you
-ralph

**Comment by gustavooferreira** [comment]
Hey Ralph,

I was first kinda asking for permission :b

I have just made a PR. If you think I should change something, just let me know and I will do it.
